### ISSUE TITLE
Do not overwrite prompt artifacts

### ISSUE THREAD

**Issue by gabe-l-hart** [caikit/caikit-tgis-backend#51]
## Describe the bug

The [current implementation of `load_prompt_artifacts`](https://github.com/caikit/caikit-tgis-backend/blob/main/caikit_tgis_backend/tgis_connection.py#L230) is very inefficient when there are multiple replicas of `caikit.runtime` running with shared volume mounts. As written, the prompt files will be copied over on _every_ model load across all replicas, regardless of whether the files already exist in the destination.

Prompts themselves are immutable in TGIS, so we don't need to support the case where the source artifacts are an updated version of the previously copied artifacts. The simple solution, therefore is to simply not copy files when the target already exists.

The main error-case that would still need to be handled is fixing a corrupted file. If the target file is only a partial copy (e.g. a replica was killed in the middle of uploading a prompt file), a simple `os.path.exists` check will cause future attempts to re-copy to fail.

**Comment by joerunde** [comment]
> If the target file is only a partial copy

Given the history of liveness probes killing caikit pods, I'd expect users to run into this case

**Comment by mynhardtburger** [comment]
Should some form of batching be done, with a recheck of which files needs to be copied in between each batch?

If there is a large amount of files to be copied and multiple pods are starting. There will be significant overlap in the queue of planned files to be copied between the pods. With s3fs like mounts file listing operations are expensive operation due to network latencies.

When the list of files to be copied is large (eg. > 50) working through the backlog using randomized batches, and updating the backlog (get new file listing) between batches could minimize the overlap.
